<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Geometry and model parameters for SLAMBot -->
  <!-- Visual/body dimensions -->
  <xacro:property name="robot_length" value="0.297"/>
  <xacro:property name="robot_width"  value="0.152"/>
  <xacro:property name="robot_height" value="0.08"/>

  <!-- Wheel geometry -->
  <xacro:property name="wheel_radius" value="0.0485"/>
  <xacro:property name="wheel_thickness" value="0.048"/>

  <!-- Real-life wheel-center geometry (controls kinematics) -->
  <xacro:property name="base_length" value="0.21"/>
  <xacro:property name="base_width"  value="0.200"/>

  <!-- Convenience: half distances -->
  <xacro:property name="wheel_x" value="${base_length/2.0}"/>
  <xacro:property name="wheel_y" value="${base_width/2.0}"/>

  <!-- Battery pack -->
  <xacro:property name="battery_depth" value="0.051"/>
  <xacro:property name="battery_width" value="0.177"/>

</robot>

