odom_node:
  ros__parameters:
    wheel_radius: 0.0485
    base_length: 0.212
    base_width: 0.194
    ticks_per_rev: 2882.0
    encoder_topic: "/wheel_encoders"
    odom_topic: "/odom"
    odom_frame: "odom"
    base_frame: "base_link"
    initial_x: 0.0
    initial_y: 0.0
    initial_theta: 0.0
    covariance_base: 0.5
    covariance_y_multiplier: 10.0
    pose_to_twist_covariance_scale: 0.5
    ignored_axis_covariance: 1000000.0
