mecanum_drive_controller:
  ros__parameters:
    i2c_device: "/dev/i2c-1"
    i2c_address: 18
    encoder_publish_period_ms: 50
    cmd_vel_topic: "/cmd_vel"
    encoder_topic: "/wheel_encoders"
    wheel_radius: 0.0485
    base_length: 0.212
    base_width: 0.194
    ticks_per_rev: 2882.0
    max_ticks_per_sec: 3500.0
    max_linear_speed_mps: 0.35
    max_angular_speed_radps: 1.5
    kp: 0.5
    ki: 0.00001
    kd: 0.0
    kp_hold: 5.0
    ki_hold: 0.0
    kd_hold: 0.0
