cmake_minimum_required(VERSION 3.8)
project(paesano_orchestrator)

find_package(ament_cmake REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(nav_msgs REQUIRED)
find_package(paesano_navigation REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rclcpp_action REQUIRED)
find_package(std_msgs REQUIRED)
find_package(std_srvs REQUIRED)
find_package(tf2 REQUIRED)
find_package(tf2_geometry_msgs REQUIRED)

add_executable(orchestrator_node src/orchestrator.cpp src/orchestrator_tick.cpp)
target_include_directories(orchestrator_node PRIVATE include)
ament_target_dependencies(orchestrator_node geometry_msgs nav_msgs paesano_navigation rclcpp rclcpp_action std_msgs std_srvs tf2 tf2_geometry_msgs)

install(TARGETS orchestrator_node DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY launch config DESTINATION share/${PROJECT_NAME})
ament_package()
